Repository kiwix/kiwix-apple, pull requests merged in 2024-10, with the labels that each got.

#995 994 - Extend 'immerse reading' for iPad as well
  Views/BuildingBlocks/WebView.swift
Labels: enhancement, iOS

#997 corrected name of config flag
  README.md
Labels: enhancement

#999 Avoid crash on iOS 18
  Views/BuildingBlocks/WebView.swift
Labels: bug, iOS

#1008 Improve launch sequence for custom apps
  App/App_macOS.swift
  App/CompactViewController.swift
  App/SplitViewController.swift
  ViewModel/BrowserViewModel.swift
  ViewModel/LaunchViewModel.swift
  Views/BrowserTab.swift
  Views/BuildingBlocks/LoadingView.swift
  Views/LocalLibraryList.swift
  Views/Welcome.swift
  Views/WelcomeCatalog.swift
Labels: enhancement, macOS, iOS, custom apps

#1014 Use webView loading while restoring a tab
  ViewModel/BrowserViewModel.swift
Labels: bug
