Repository kiwix/kiwix-apple, pull requests merged in 2024-09, with the labels that each got.

#960 Error handling for catalog not available 503
  Tests/LibraryRefreshViewModelTest.swift
  ViewModel/LibraryViewModel.swift
  Views/BuildingBlocks/Message.swift
  Views/Library/ZimFilesCategories.swift
  Views/Library/ZimFilesNew.swift
  Views/Settings/Settings.swift
  Views/Welcome.swift
Labels: enhancement, macOS, iOS

#965 Fix snippets' color
  Views/BuildingBlocks/ArticleCell.swift
Labels: bug, iOS

#956 Migration services added
  Model/Migration/MigrationService.swift
  Tests/MigrationServiceTests.swift
Labels: enhancement, macOS, iOS

#968 Fix opening app with ZIM doesn't open ZIM
  App/App_macOS.swift
  CHANGELOG.md
  ViewModel/BrowserViewModel.swift
Labels: bug

#977 Fix search results snippet and sorting issue
  SwiftUI/Model/SearchOperation/SearchOperation.swift
Labels: bug, question

#982 Fix video only on active scene
  Views/BrowserTab.swift
Labels: bug, iOS

#981 Remove duplicate search entries
  SwiftUI/Model/SearchOperation/SearchOperation.h
  SwiftUI/Model/SearchOperation/SearchOperation.mm
Labels: bug, macOS, iOS

#974 861 library loading is blocking the main thread
  App/App_iOS.swift
  App/App_macOS.swift
  Model/DownloadService.swift
  Model/Utilities/WebKitHandler.swift
  Model/ZimFileService/ZimContentProvider.swift
  Model/ZimFileService/ZimFileService.h
  Model/ZimFileService/ZimFileService.mm
  Model/ZimFileService/ZimFileService.swift
  SwiftUI/Model/LibraryOperations.swift
  ViewModel/BrowserViewModel.swift
  ViewModel/LibraryViewModel.swift
  ViewModel/SearchViewModel.swift
  Views/BuildingBlocks/ZimFileCell.swift
  Views/Buttons/AsyncButton.swift
  Views/Buttons/AsyncButtonView.swift
  Views/Library/Library.swift
  Views/Library/ZimFileDetail.swift
  Views/ViewModifiers/FileImport.swift
  Views/ViewModifiers/SaveContentHandler.swift
  Views/ViewModifiers/ViewModifiers.swift
  Views/Welcome.swift
Labels: enhancement, macOS, iOS

#987 Replace DispatchQueues with async Tasks
  App/App_macOS.swift
  Model/DownloadService.swift
  Model/Utilities/InSync.swift
  ViewModel/BrowserViewModel.swift
  ViewModel/SearchViewModel.swift
  Views/Library/ZimFilesOpened.swift
  Views/SearchResults.swift
  Views/ViewModifiers/FileImport.swift
Labels: enhancement, macOS, iOS

#989 Remove OrderedCollections dependency
  Tests/OrderedCacheTests.swift
  ViewModel/BrowserViewModel.swift
  ViewModel/OrderedCache.swift
  project.yml
Labels: enhancement
